language: cpp

os:
  - linux
  - osx
  
dist: trusty
sudo: required

# OS X only supports one image. Use the latest.
osx_image: xcode8.3

git:
  depth: 3
  
compiler:
  - clang
  - gcc
  
env:
  global:
    - BUILD_JOBS=2
  matrix:
    - BUILD_MODE="all"
    - BUILD_MODE="no-asm"
    - BUILD_MODE="asan"
    - BUILD_MODE="ubsan"
    - BUILD_MODE="codecov"
    
matrix:
  exclude:
    # Skip GCC on OS X entirely
    - os: osx
      compiler: gcc
    # CodeCov crashes under Clang
    - compiler: clang
      env: BUILD_MODE="codecov"
  allow_failures:
    # Ignore problems with old toolchains
    - env: BUILD_MODE="ubsan"
    - env: BUILD_MODE="asan"
    
script:
  - make "$BUILD_MODE" && make test && ./cryptest.exe tv all
  
after_success:
  - if [[ ( ("$BUILD_MODE" = "coverage") && ("$CC" = "gcc") ) ]]; then CODECOV_TOKEN="5c7bc59c-e95f-4594-82c3-33e7a1942592" bash <(curl -s https://codecov.io/bash); fi;
  
# whitelist branches to avoid testing feature branches twice
branches:
  only:
    - master
    
addons:
  sonarqube: true
  coverity_scan:
    project:
      name: "cryptopp"
    build_command: "make -j 4"
    
notifications:
  email:
    recipients:
      - uri@mit.edu
    on_success: always # default: change
    on_failure: always # default: always
